# Generated by Django 5.0.4 on 2024-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_adminsecret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsecret',
            name='secret',
        ),
        migrations.AddField(
            model_name='adminsecret',
            name='api_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
